name: Azure Sentinel KQL Import Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  import-kql:
    runs-on: ubuntu-latest
    environment: azure

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: requirements.txt

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8

    - name: Run static code analysis
      run: |
        flake8 sentinel_pipeline.py tests/ --max-line-length=120

    - name: Lint KQL files
      run: |
        for file in $(find . -name "*.kql"); do
          if ! grep -q "TimeGenerated" "$file"; then
            echo "Error: $file missing TimeGenerated filter"
            exit 1
          fi
          if grep -qi "search" "$file"; then
            echo "Error: $file contains deprecated 'search' operator"
            exit 1
          fi
        done

    - name: Scan dependencies for vulnerabilities
      run: |
        pip install safety
        safety check -r requirements.txt

    - name: Run unit tests with coverage
      run: |
        pytest tests/ --cov=sentinel_pipeline --cov-report=xml --cov-fail-under=90 --junitxml=test-results.xml
        coverage report -m

    - name: Upload coverage report
      uses: codecov/codecov-action@v4
      with:
        files: ./coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Run Sentinel Pipeline
      env:
        SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        RESOURCE_GROUP_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}
        WORKSPACE_NAME: ${{ secrets.WORKSPACE_NAME }}
        AZURE_LOCATION: ${{ secrets.AZURE_LOCATION }}
        QUERY_PACK_NAME: ${{ secrets.QUERY_PACK_NAME }}
      run: python sentinel_pipeline.py

    - name: Archive logs and metrics
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: pipeline-artifacts
        path: |
          sentinel_pipeline.log
          coverage.xml
          test-results.xml