name: Import Sigma Rules

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC

jobs:
  import-rules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Validate secrets
      run: |
        if [[ "${{ secrets.PROVIDER }}" == "aws" && -z "${{ secrets.AWS_REGION }}" ]]; then
          echo "Error: AWS_REGION is required for PROVIDER=aws"
          exit 1
        fi
        if [[ -z "${{ secrets.OPENSEARCH_HOST }}" || -z "${{ secrets.OPENSEARCH_PORT }}" || -z "${{ secrets.OPENSEARCH_SCHEME }}" ]]; then
          echo "Error: OPENSEARCH_HOST, OPENSEARCH_PORT, and OPENSEARCH_SCHEME are required"
          exit 1
        fi

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Scan Docker image for vulnerabilities
      run: |
        docker run --rm aquasec/trivy image --exit-code 1 --severity HIGH,CRITICAL sigma-importer || true

    - name: Build and run Docker container
      env:
        OPENSEARCH_HOST: ${{ secrets.OPENSEARCH_HOST }}
        OPENSEARCH_PORT: ${{ secrets.OPENSEARCH_PORT }}
        OPENSEARCH_SCHEME: ${{ secrets.OPENSEARCH_SCHEME }}
        OPENSEARCH_USERNAME: ${{ secrets.OPENSEARCH_USERNAME }}
        OPENSEARCH_PASSWORD: ${{ secrets.OPENSEARCH_PASSWORD }}
        PROVIDER: ${{ secrets.PROVIDER }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        CONFIG_PATH: config.yaml
        METRICS_PORT: 8000
      run: |
        docker build -t sigma-importer .
        docker run --rm \
          -e HOST=${OPENSEARCH_HOST} \
          -e PORT=${OPENSEARCH_PORT} \
          -e SCHEME=${OPENSEARCH_SCHEME} \
          -e USERNAME=${OPENSEARCH_USERNAME} \
          -e PASSWORD=${OPENSEARCH_PASSWORD} \
          -e PROVIDER=${PROVIDER} \
          -e AWS_REGION=${AWS_REGION} \
          -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} \
          -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} \
          -e AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN} \
          -e CONFIG_PATH=${CONFIG_PATH} \
          -e METRICS_PORT=${METRICS_PORT} \
          sigma-importer

    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: sigma-import-logs
        path: sigma_import.log

    - name: Notify on failure
      if: failure()
      uses: slackapi/slack-github-action@v1.27.0
      with:
        slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
        channel-id: 'security-alerts'
        text: 'Sigma rule import job failed. ${{ steps.import-rules.outputs.failed_files }} Check GitHub Actions logs and sigma_import.log artifact for details.'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}